# Async Options
title:      Async
caption:    A JavaScript meetup for _Brighton & Hove_
url:        http://asyncjs.com
email:      hello@asyncjs.com
feedburner: http://feeds.feedburner.com/asyncjs
analytics:  UA-2150808-14
mapbox:
  api_token: pk.eyJ1IjoiYXN5bmNqcyIsImEiOiJrMHlGX3BJIn0.O57e5qvXpxKni60engPX2Q

elsewhere:
- name: News
  link: /news/
  desc: Recent Async Announcements
- name: Twitter
  link: http://twitter.com/asyncjs
  desc: Follow @asyncjs on Twitter
- name: Facebook
  link: https://www.facebook.com/pages/Async/533002916854919
  desc: Like our page on Facebook
- name: Mailing List
  link: http://groups.google.com/group/asyncjs/
  desc: Email list on Google Groups
- name: Subscribe to feed
  link: /feed/
  desc: Subscribe to the website's Atom feed
- name: Subscribe by email
  link: http://feedburner.google.com/fb/a/mailverify?uri=asyncjs
  desc: Subscribe to email updates for the website
- name: Lanyrd
  link: http://lanyrd.com/series/asyncjs/
  desc: Async events on Lanyrd
- name: Calendar
  link: http://lanyrd.com/series/asyncjs/save-to-calendar/
  desc: Subscribe to our calendar
- name: Email Us
  link: "&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#104;&#101;&#108;&#108;&#111;&#64;&#97;&#115;&#121;&#110;&#99;&#106;&#115;&#46;&#99;&#111;&#109;"
  desc: Get in touch
- name: Slack
  link: mailto:hello@asyncjs.com?Subject=Please%20add%20me%20to%20the%20Async%20Slack%20channel
  desc: "Request access to the Async Slack channel"
- name: Code of Conduct
  link: /codeofconduct/
  desc: View our code of conduct


# Jekyll Options
safe:        true
baseurl:

source:      .
destination: /tmp/asyncjs
exclude:
- bin
- Makefile
- README.md
future:      true
timezone:    UCT
lsi:         false
highlighter: false
markdown:    kramdown
permalink:   /:title/
